import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import DarkMode from "@/components/DarkMode/DarkMode"

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
})

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
})

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}


import localFont from 'next/font/local'

const yekan = localFont({
  src:'./font/Yekan.woff',
  variable: '--font-yekan',
  display: 'swap'
})

export default function RootLayout({ children }) {
   return (
      <html lang="fa" className={yekan.variable}>
         <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
            <DarkMode></DarkMode>
            {children}
         </body>
      </html>
   )
}
